version: "3.9"
services:
  bare-img:
    build:
      context: ./
      target: dev
    ports:
      - "5000:5000"
    command: "npm run start:dev"
    volumes:
      - .:/app
      - ./images:/images
